### ISSUE TITLE
В чём смысл LevelConfigEditor?

### ISSUE THREAD

**Issue by Red-Cat-Fat** [shark2302/TowerDefence#4]
По коду он просто отрисовывает все элементы выбранного конфига. По факту он и без этого скрипта прекрасно отображал все поля.

**Comment by Red-Cat-Fat** [comment]
То же самое относится и к LevelConfigEditor. По факту можно было отписать к одному и тому же скрипту атрибуты 
```
[CustomEditor(typeof(LevelConfig))]
[CustomEditor(typeof(SpawnerConfig))]
```
И ничего не изменилось бы

**Comment by shark2302** [comment]
Ну это я пытался разобраться с эдитором, поэтому сделал такую бессмыслицу
