### ISSUE TITLE
NRE

### ISSUE THREAD

**Issue by Red-Cat-Fat** [shark2302/TowerDefence#5]
https://github.com/shark2302/TowerDefence/blob/93f9b930581cf17a7f3c3c90dbacdc1aa9faf501/Assets/Scripts/Objects/UnitSpawner.cs#L43-L44

**Comment by shark2302** [comment]
Почему именно это плохо?

**Comment by Red-Cat-Fat** [comment]
Потому, что геймдизайнер по обыкновению своему может разместить в лист спавна префаб, который не содержит в себе UnitController, а ты даже не удосужился проверить его наличие при спавне

**Comment by shark2302** [comment]
теперь проверяю https://github.com/shark2302/TowerDefence/commit/42605c447a1489fb585e5a6b9d56f2a10c0cdefc

**Comment by Red-Cat-Fat** [comment]
Вообще надо было сделать переменные приватными, а свойства публичными, чтобы инкапсулировать сами значения
