### ISSUE TITLE
Не используй рефлексию

### ISSUE THREAD

**Issue by Red-Cat-Fat** [shark2302/TowerDefence#6]
Ищешь по тегам в HP - это не очень хорошо

**Comment by shark2302** [comment]
Немного не понял, можно код, где я так делаю, имеется в виду, что я проверяю тег у корректного объекта?

**Comment by Red-Cat-Fat** [comment]
Я тебе говорю, в классе HP. 
https://github.com/shark2302/TowerDefence/blob/e6c24400dc10869c793ee0ec13dd803677542ef6/Assets/Scripts/Objects/HP.cs#L26

**Comment by shark2302** [comment]
так это вроде как не рефлексия, Макар на лекции рассказывал, что это нормально, я же беру тег у данного объекта

**Comment by Red-Cat-Fat** [comment]
Обращение к тегу происходит через текстовое поле. Малейшее изменения в поле тега дизайнерами - и код перестаёт работать. Так делать нельзя.

**Comment by shark2302** [comment]
а есть какой-то подобный способ проверять, чем является объект?

**Comment by shark2302** [comment]
Разумно ли накинуть на объект пустой скрипт, DestroyableObject?

**Comment by shark2302** [comment]
https://github.com/shark2302/TowerDefence/commit/13e78831f4dbaa1cc75e7476258fbeea41a02c67 пока сделал булку, которая говорит есть ли анмация или нет, чтобы не брать тег

**Comment by Red-Cat-Fat** [comment]
Тут скорее надо дёргать "Смерть" в любом случае, чем тратить время на настройки галки, про которую могут забить.

> А есть какой-то подобный способ проверять, чем является объект?

Да - брать с него компонент, который соответствует тому или иному типу объектов

> Разумно ли накинуть на объект пустой скрипт, DestroyableObject?

Да, вполне, но всё же стоит накинуть туда хоть какую-то логику) Чтобы он выполнял какую-то работу. Например именно его заставлять дестроиться весь обж

**Comment by shark2302** [comment]
Теперь дергаю сразу смерть, для этого в аниматоры забора и башни, добавил тригер, который не используется https://github.com/shark2302/TowerDefence/commit/7b174550ac2777f96a1ff9d1f7652a5e65acc2f0
